PATH="$PATH:$HOME/.local/bin:$GOROOT/bin:$GOPATH/bin"

export EDITOR=vim
export TERM='xterm-256color'
export VISUAL=vim

#aws-cli ENV
export AWS_DEFAULT_REGION=us-east-1
export AWS_CLI_AUTO_PROMPT=on-partial
export AWS_PAGER=

#GO
export GOPATH=$HOME/.local/projects/go
export GOROOT=$HOME/.local/bin/go

#USER AGENT
export AGENT='Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36'
