name: Publish Docker Image
on: 
  push:
    branches:
      - 'main'
  schedule:
    - cron: '21 11 * * *'
jobs:
  docker:
    runs-on: ubuntu-latest
    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: fonalex45/bounty-sec:latest
      -
        name: Notify Slack Channel of finished build
        uses: act10ns/slack@v1
        with:
          status: ${{ job.status }}
          channel: '#general'
        if: always()
